[package]
name = "valkyrie-parser"
version = "0.0.1"
authors = ["192608617@qq.com"]
edition = "2018"
description = "..."
repository = "https://github.com/nyar-lang/NyarNative"
license = "MPL-2.0"


[dependencies]

[dependencies.valkyrie-pest]
path = "../valkyrie-pest"
version = "0.1"

[dependencies.nyar-hir]
path = "../nyar-hir"
version = "0.1"

[dev-dependencies]


[build-dependencies]
