[package]
name = "valkyrie-parser"
version = "0.2.0"
authors = ["192608617@qq.com"]
edition = "2018"
description = "..."
repository = "https://github.com/nyar-lang/NyarNative"
license = "MPL-2.0"


[dependencies]
# lazy_static = "1.4"

[dependencies.valkyrie-pest]
path = "../valkyrie-pest"
version = "0.2"

[dependencies.nyar-hir]
path = "../nyar-hir"
version = "0.2"

[dev-dependencies]


[build-dependencies]
