[package]
name = "nyar-number"
version = "0.0.5"
authors = ["aster <aster@mugen.vip>"]

[lib]
crate-type = ["dylib", "rlib"]
name = "number"
path = "src/lib.rs"


[dependencies]
bigdecimal = "0.1.0"
serde_json = "1.0.40"
rand = "0.7.0"
gc = {version = "0.3.3", optional = true}
num = {version = "0.2", default-features = true}