[package]
name = "Algebra"
version = "0.0.5"
authors = ["aster <aster@mugen.vip>"]

[lib]
name = "nyar_lib"
path = "src/mod.rs"


[dependencies]
bigdecimal = "*"
serde_json = "*"
rand = "*"

[dependencies.num]
version = "0.2"
default-features = true