[workspace]

members = ["projects/*"]
default-members = [
    "projects/nyar-interpreter",
    "projects/nyar-ast",
    "projects/valkyrie-parser",
    "projects/sijuiacion-codegen",
]

[profile.release]
lto = true
opt-level = "s"