[package]
name = "nyar-hir"
version = "0.2.2"
authors = ["192607617@qq.com"]
edition = "2021"
description = "High level intermediate representation for Nyar"
repository = "https://github.com/nyar-lang/NyarNative"
license = "MPL-2.0"

[dependencies]
serde = { version = "1.0.152", features = ["derive"] }
pretty = { version = "0.11.3", features = ["termcolor"] }

[dependencies.nyar-error]
#version = "0.1.4"
path = "../nyar-error"




[dev-dependencies]

[features]
default = []
