[package]
name = "valkyrie-language-server"
version = "0.2.0"
authors = ["192608617@qq.com"]
edition = "2018"
description = "..."
repository = "https://github.com/nyar-lang/NyarNative"
license = "MPL-2.0"

[[bin]]
name = "vls"
path = "src/main.rs"

[dependencies]
clap = { version = "4.0.32", features = ["derive"] }
tokio = { version = "1.15.0", features = ["full"] }

[dev-dependencies]

[build-dependencies]
