[package]
name = "wast-encoder"
version = "0.1.0"
categories = ["wasm"]
keywords = ["webassembly", "wasm"]
description = "WAST encoder supporting wasi and wit components"
repository = "https://github.com/oovm/vcc"
documentation = "https://docs.rs/wast-encoder"
readme = "readme.md"
license = "MPL-2.0"
edition = "2021"
exclude = ["package.json", "tests/**"]

[dependencies]


[dev-dependencies]

[features]
wast = []
