[package]
name = "nyar_vanilla"
version = "0.0.1"
authors = ["192608617@qq.com"]
edition = "2018"
description = "..."
repository = "https://github.com/nyar-lang/NyarNative"
license = "MPL-2.0"

[dependencies]
pest = "2.1.0"
pest_derive = "2.1.0"

[dev-dependencies]


[build-dependencies]
