[package]
name = "nyar-wasm"
version = "0.0.0"
authors = ["Aster <192607617@qq.com>"]
description = "High level wasm builder"
repository = "https://github.com/oovm/dialect"
documentation = "https://docs.rs/pliron-wasm"
readme = "readme.md"
license = "MPL-2.0"
edition = "2021"
exclude = ["package.json", "tests/**"]

[dependencies]
indexmap = "2.1.0"
wasmprinter = "0.2.75"
wasm-encoder = "0.38.1"

[dependencies.nyar-error]
version = "0.1.*"
path = "../nyar-error"

[dependencies.nyar-hir]
version = "0.2.*"
path = "../nyar-hir"

[dependencies.wasmtime]
version = "15.0.1"
features = ["component-model"]

[dev-dependencies]

[features]
default = []

[package.metadata.docs.rs]
all-features = true
