[package]
name = "nyar-wasm"
version = "0.0.0"
authors = ["Aster <192607617@qq.com>"]
description = "..."
repository = "https://github.com/nyar-vm/valkyrie.rs"
documentation = "https://docs.rs/sub_projects"
readme = "Readme.md"
license = "MPL-2.0"
edition = "2021"

[dependencies]
wasmtime = "15.0.0"
anyhow = "1.0.75"

[dependencies.nyar-error]
version = "0.1.10"
path = "../nyar-error"
features = ["wasmtime"]

[dev-dependencies]

[features]
default = []
