[package]
name = "wepl"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 WITH LLVM-exception"
categories = ["wasm"]
keywords = ["webassembly", "wasm"]
repository = "https://github.com/rylev/wepl"

[dependencies]
anyhow = "1.0"
async-trait = "0.1.77"
clap = { version = "4.5.0", features = ["derive"] }
bytes = "1.5.0"
env_logger = "0.11"
home = "0.5.9"
log = "0.4"
nom = "7.1.3"
nom_locate = "4.2"
rustyline = "13.0.0"
colored = "2"
tokio = { version = "1.36.0", features = ["macros"] }

wasmtime = { version = "18.0.1", features = [ "component-model", "async"] }
wasmtime-wasi = { version = "18.0.1", features = [ "tokio", ] }
wasi-virt = { git = "https://github.com/bytecodealliance/WASI-Virt", rev = "fd2fae04342ea58aab2426ca041da68be046b030" }
wit-component = "0.200.0"
wit-parser = "0.200.0"
wasm-compose = "0.200.0"
